-- Generated by scripts/upload_microorganism_images.js
-- Exactly 47 validated Cloudinary images mapped by microorganisms.display_order.
-- This SQL preserves existing media.documents and replaces only each record's images array.

BEGIN;
ALTER TABLE microorganisms
  ADD COLUMN IF NOT EXISTS display_order integer,
  ADD COLUMN IF NOT EXISTS media JSONB NOT NULL DEFAULT '{"images": [], "documents": []}'::jsonb;

DO $$
BEGIN
  IF (SELECT COUNT(*) FROM microorganisms WHERE display_order BETWEEN 1 AND 47) <> 47 THEN
    RAISE EXCEPTION 'Expected exactly 47 microorganism records with display_order 1-47';
  END IF;
END $$;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180723/microorganisms/images/staphylococcus/1.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180723/microorganisms/images/staphylococcus/1.png","public_id":"microorganisms/images/staphylococcus/1","resource_type":"image","format":"png","width":429,"height":354,"caption":"Microbial strain 1","source_file":"Picture1.png","source_folder":"staphylococcus","source_sha256":"d3a5ccfe30bd2f388a86e522b05ca431ce931b98f0bb238807828656a606eb7c"}'::jsonb), true)
WHERE display_order = 1;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180724/microorganisms/images/staphylococcus/2.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180724/microorganisms/images/staphylococcus/2.png","public_id":"microorganisms/images/staphylococcus/2","resource_type":"image","format":"png","width":356,"height":350,"caption":"Microbial strain 2","source_file":"Picture2.png","source_folder":"staphylococcus","source_sha256":"744921d48da4d964212094b87ef3e54f14db2575d4ae8920c921ae430e39f7e8"}'::jsonb), true)
WHERE display_order = 2;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180725/microorganisms/images/staphylococcus/3.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180725/microorganisms/images/staphylococcus/3.png","public_id":"microorganisms/images/staphylococcus/3","resource_type":"image","format":"png","width":377,"height":347,"caption":"Microbial strain 3","source_file":"Picture3.png","source_folder":"staphylococcus","source_sha256":"afdc71efdcbaf190245abff4d1180d63f6cb3094b3a886797a4b65215377ff7b"}'::jsonb), true)
WHERE display_order = 3;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180726/microorganisms/images/staphylococcus/4.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180726/microorganisms/images/staphylococcus/4.png","public_id":"microorganisms/images/staphylococcus/4","resource_type":"image","format":"png","width":431,"height":338,"caption":"Microbial strain 4","source_file":"Picture4.png","source_folder":"staphylococcus","source_sha256":"0ac15baa433b5c50c1b134a4d2c6979889aa24632938f474f5d33915530d69de"}'::jsonb), true)
WHERE display_order = 4;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180728/microorganisms/images/staphylococcus/5.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180728/microorganisms/images/staphylococcus/5.png","public_id":"microorganisms/images/staphylococcus/5","resource_type":"image","format":"png","width":368,"height":335,"caption":"Microbial strain 5","source_file":"Picture5.png","source_folder":"staphylococcus","source_sha256":"d8cfa8430723ed5d83e622b05c16c86c8d501b2e5f4fc8384aabae8085dd9dee"}'::jsonb), true)
WHERE display_order = 5;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180729/microorganisms/images/staphylococcus/6.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180729/microorganisms/images/staphylococcus/6.png","public_id":"microorganisms/images/staphylococcus/6","resource_type":"image","format":"png","width":396,"height":336,"caption":"Microbial strain 6","source_file":"Picture6.png","source_folder":"staphylococcus","source_sha256":"429f728d02c7c3054fe300602733212202bd99ce826627e3d2114c9224d6dfd7"}'::jsonb), true)
WHERE display_order = 6;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180730/microorganisms/images/staphylococcus/7.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180730/microorganisms/images/staphylococcus/7.png","public_id":"microorganisms/images/staphylococcus/7","resource_type":"image","format":"png","width":419,"height":396,"caption":"Microbial strain 7","source_file":"Picture7.png","source_folder":"staphylococcus","source_sha256":"bbc3c058017eab422dcec6ce2ba1b64798b6d10c7cbf8c113505da3f8e23f339"}'::jsonb), true)
WHERE display_order = 7;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180732/microorganisms/images/staphylococcus/8.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180732/microorganisms/images/staphylococcus/8.png","public_id":"microorganisms/images/staphylococcus/8","resource_type":"image","format":"png","width":373,"height":397,"caption":"Microbial strain 8","source_file":"Picture8.png","source_folder":"staphylococcus","source_sha256":"5db870708638642687ca8395c5be983d3b019f85261fb108ce008f6e1450ed90"}'::jsonb), true)
WHERE display_order = 8;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180734/microorganisms/images/staphylococcus/9.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180734/microorganisms/images/staphylococcus/9.png","public_id":"microorganisms/images/staphylococcus/9","resource_type":"image","format":"png","width":405,"height":405,"caption":"Microbial strain 9","source_file":"Picture9.png","source_folder":"staphylococcus","source_sha256":"b6a38e279d1cd9907ca6a4a3b7b8d36bc1b913e21b63bcf36c828a9e480c81eb"}'::jsonb), true)
WHERE display_order = 9;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180736/microorganisms/images/staphylococcus/10.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180736/microorganisms/images/staphylococcus/10.png","public_id":"microorganisms/images/staphylococcus/10","resource_type":"image","format":"png","width":412,"height":358,"caption":"Microbial strain 10","source_file":"Picture10.png","source_folder":"staphylococcus","source_sha256":"59d4f5dba41d30282fe08b54f94a2813686cbd6db14e710edde47fcbeec85eec"}'::jsonb), true)
WHERE display_order = 10;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180738/microorganisms/images/staphylococcus/11.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180738/microorganisms/images/staphylococcus/11.png","public_id":"microorganisms/images/staphylococcus/11","resource_type":"image","format":"png","width":377,"height":353,"caption":"Microbial strain 11","source_file":"Picture11.png","source_folder":"staphylococcus","source_sha256":"ff74e3026a169216fe28790ce54ce8d5a2684182232f16d3db923e9e813dd62e"}'::jsonb), true)
WHERE display_order = 11;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180740/microorganisms/images/staphylococcus/12.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180740/microorganisms/images/staphylococcus/12.png","public_id":"microorganisms/images/staphylococcus/12","resource_type":"image","format":"png","width":405,"height":357,"caption":"Microbial strain 12","source_file":"Picture12.png","source_folder":"staphylococcus","source_sha256":"8def7cff13fedeb06685dfce1fe04147fea7608feaff61b13688a52fb601b3e8"}'::jsonb), true)
WHERE display_order = 12;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180741/microorganisms/images/staphylococcus/13.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180741/microorganisms/images/staphylococcus/13.png","public_id":"microorganisms/images/staphylococcus/13","resource_type":"image","format":"png","width":412,"height":422,"caption":"Microbial strain 13","source_file":"Picture13.png","source_folder":"staphylococcus","source_sha256":"ff68413d482f40b0c6e75d94288ceb905391038b402d3da80ee36747c274bcce"}'::jsonb), true)
WHERE display_order = 13;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180744/microorganisms/images/staphylococcus/14.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180744/microorganisms/images/staphylococcus/14.png","public_id":"microorganisms/images/staphylococcus/14","resource_type":"image","format":"png","width":380,"height":414,"caption":"Microbial strain 14","source_file":"Picture14.png","source_folder":"staphylococcus","source_sha256":"3453e375d7e3f6963a590f864f2e704d8db5dde284c0e22ad06e2990a9920441"}'::jsonb), true)
WHERE display_order = 14;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180746/microorganisms/images/staphylococcus/15.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180746/microorganisms/images/staphylococcus/15.png","public_id":"microorganisms/images/staphylococcus/15","resource_type":"image","format":"png","width":411,"height":410,"caption":"Microbial strain 15","source_file":"Picture15.png","source_folder":"staphylococcus","source_sha256":"0d763286d68b235e8c4b12592737c8a0c3bb39aa8d9139944d5aa833881d47cf"}'::jsonb), true)
WHERE display_order = 15;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180749/microorganisms/images/staphylococcus/16.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180749/microorganisms/images/staphylococcus/16.png","public_id":"microorganisms/images/staphylococcus/16","resource_type":"image","format":"png","width":426,"height":383,"caption":"Microbial strain 16","source_file":"Picture16.png","source_folder":"staphylococcus","source_sha256":"f6a05e364c35e80bc9275c61aa24f9c77c35d6f6569e946991099193df93adbb"}'::jsonb), true)
WHERE display_order = 16;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180752/microorganisms/images/staphylococcus/17.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180752/microorganisms/images/staphylococcus/17.png","public_id":"microorganisms/images/staphylococcus/17","resource_type":"image","format":"png","width":431,"height":396,"caption":"Microbial strain 17","source_file":"Picture17.png","source_folder":"staphylococcus","source_sha256":"3a390345a72024425b59132171104b10b230dcbf42306bebc9afafcaa28ef9be"}'::jsonb), true)
WHERE display_order = 17;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180754/microorganisms/images/staphylococcus/18.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180754/microorganisms/images/staphylococcus/18.png","public_id":"microorganisms/images/staphylococcus/18","resource_type":"image","format":"png","width":455,"height":394,"caption":"Microbial strain 18","source_file":"Picture18.png","source_folder":"staphylococcus","source_sha256":"3ae3f0fc44124430bf9e9cdf53b13225312ae6d9ffd1b87e642fd0f871bd09a1"}'::jsonb), true)
WHERE display_order = 18;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180756/microorganisms/images/staphylococcus/19.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180756/microorganisms/images/staphylococcus/19.png","public_id":"microorganisms/images/staphylococcus/19","resource_type":"image","format":"png","width":429,"height":406,"caption":"Microbial strain 19","source_file":"Picture19.png","source_folder":"staphylococcus","source_sha256":"9d76dcfa104c72d76a862ae8ea74fcdf276ce0534cc605b309cb10c48976d197"}'::jsonb), true)
WHERE display_order = 19;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180758/microorganisms/images/staphylococcus/20.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180758/microorganisms/images/staphylococcus/20.png","public_id":"microorganisms/images/staphylococcus/20","resource_type":"image","format":"png","width":438,"height":400,"caption":"Microbial strain 20","source_file":"Picture20.png","source_folder":"staphylococcus","source_sha256":"340235b84ae311cb69b0ce27de21e0ec08b8a9833d554c810c3ab7b51a2f9dc6"}'::jsonb), true)
WHERE display_order = 20;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180760/microorganisms/images/staphylococcus/21.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180760/microorganisms/images/staphylococcus/21.png","public_id":"microorganisms/images/staphylococcus/21","resource_type":"image","format":"png","width":451,"height":403,"caption":"Microbial strain 21","source_file":"Picture21.png","source_folder":"staphylococcus","source_sha256":"ec3cb2eeaed0ae39f1dd20fdacbcc07da389497a9b1502929f0f59f4852eb5fa"}'::jsonb), true)
WHERE display_order = 21;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180762/microorganisms/images/staphylococcus/22.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180762/microorganisms/images/staphylococcus/22.png","public_id":"microorganisms/images/staphylococcus/22","resource_type":"image","format":"png","width":429,"height":382,"caption":"Microbial strain 22","source_file":"Picture22.png","source_folder":"staphylococcus","source_sha256":"0292b7e631e747a195e8e4e279620e33ded04a93a0d1e7c18a34af3747cb1c88"}'::jsonb), true)
WHERE display_order = 22;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180765/microorganisms/images/staphylococcus/23.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180765/microorganisms/images/staphylococcus/23.png","public_id":"microorganisms/images/staphylococcus/23","resource_type":"image","format":"png","width":432,"height":385,"caption":"Microbial strain 23","source_file":"Picture23.png","source_folder":"staphylococcus","source_sha256":"e1bb71760b5c02d25d1b4a907079c57b9bbffeae4aaae2c174f3a3e8463428b0"}'::jsonb), true)
WHERE display_order = 23;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180768/microorganisms/images/staphylococcus/24.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180768/microorganisms/images/staphylococcus/24.png","public_id":"microorganisms/images/staphylococcus/24","resource_type":"image","format":"png","width":449,"height":385,"caption":"Microbial strain 24","source_file":"Picture24.png","source_folder":"staphylococcus","source_sha256":"446fae191f472d90258636abeabc53f193629389e5e1d17b44c5aafd917f7f88"}'::jsonb), true)
WHERE display_order = 24;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180770/microorganisms/images/staphylococcus/25.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180770/microorganisms/images/staphylococcus/25.png","public_id":"microorganisms/images/staphylococcus/25","resource_type":"image","format":"png","width":432,"height":394,"caption":"Microbial strain 25","source_file":"Picture25.png","source_folder":"staphylococcus","source_sha256":"fa193a87c0b4da50fbb31b503b62cb1a50b2052293b1bdfe1d2dd7fe0b63f4c0"}'::jsonb), true)
WHERE display_order = 25;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180774/microorganisms/images/staphylococcus/26.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180774/microorganisms/images/staphylococcus/26.png","public_id":"microorganisms/images/staphylococcus/26","resource_type":"image","format":"png","width":428,"height":396,"caption":"Microbial strain 26","source_file":"Picture26.png","source_folder":"staphylococcus","source_sha256":"a7ac5932ede4b01011c595400b4bb87114d98e245ceefdf615aa4348aedc212b"}'::jsonb), true)
WHERE display_order = 26;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180778/microorganisms/images/staphylococcus/27.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180778/microorganisms/images/staphylococcus/27.png","public_id":"microorganisms/images/staphylococcus/27","resource_type":"image","format":"png","width":447,"height":394,"caption":"Microbial strain 27","source_file":"Picture27.png","source_folder":"staphylococcus","source_sha256":"77c84ede844281bf9f68c1b31278b463242822655b206140ef72c6a4b091d354"}'::jsonb), true)
WHERE display_order = 27;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180783/microorganisms/images/staphylococcus/28.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180783/microorganisms/images/staphylococcus/28.png","public_id":"microorganisms/images/staphylococcus/28","resource_type":"image","format":"png","width":423,"height":408,"caption":"Microbial strain 28","source_file":"Picture28.png","source_folder":"staphylococcus","source_sha256":"2d40180bb81c87ca52237f95df5caaea8f56ffcaef2993548e4ddc162b7806e9"}'::jsonb), true)
WHERE display_order = 28;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180791/microorganisms/images/staphylococcus/29.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180791/microorganisms/images/staphylococcus/29.png","public_id":"microorganisms/images/staphylococcus/29","resource_type":"image","format":"png","width":438,"height":407,"caption":"Microbial strain 29","source_file":"Picture29.png","source_folder":"staphylococcus","source_sha256":"7b8e45bf6db3d3aefeb562f4188cdeede300dfb9040d765c37549af2d97568ab"}'::jsonb), true)
WHERE display_order = 29;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180800/microorganisms/images/staphylococcus/30.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180800/microorganisms/images/staphylococcus/30.png","public_id":"microorganisms/images/staphylococcus/30","resource_type":"image","format":"png","width":435,"height":407,"caption":"Microbial strain 30","source_file":"Picture30.png","source_folder":"staphylococcus","source_sha256":"27b3d5cf255aee9f2bbb07a91f2e7799870692ee42b7e8fd03f370a3b3a882b7"}'::jsonb), true)
WHERE display_order = 30;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180808/microorganisms/images/staphylococcus/31.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180808/microorganisms/images/staphylococcus/31.png","public_id":"microorganisms/images/staphylococcus/31","resource_type":"image","format":"png","width":448,"height":454,"caption":"Microbial strain 31","source_file":"Picture31.png","source_folder":"staphylococcus","source_sha256":"e073cf5aba810a84dff0a0cb9263ae2c056eb147703d935048bb52a4f6217815"}'::jsonb), true)
WHERE display_order = 31;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180816/microorganisms/images/staphylococcus/32.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180816/microorganisms/images/staphylococcus/32.png","public_id":"microorganisms/images/staphylococcus/32","resource_type":"image","format":"png","width":450,"height":454,"caption":"Microbial strain 32","source_file":"Picture32.png","source_folder":"staphylococcus","source_sha256":"e86dc3e51a265a4c9bc795412c365c3ab4b126f1916de8a2aa70e58f51de4cb6"}'::jsonb), true)
WHERE display_order = 32;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180821/microorganisms/images/staphylococcus/33.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180821/microorganisms/images/staphylococcus/33.png","public_id":"microorganisms/images/staphylococcus/33","resource_type":"image","format":"png","width":404,"height":451,"caption":"Microbial strain 33","source_file":"Picture33.png","source_folder":"staphylococcus","source_sha256":"9882a854742b00e62885655e7e7671b0d86ef27b0f07c81e3859c95c75c2dee4"}'::jsonb), true)
WHERE display_order = 33;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180823/microorganisms/images/staphylococcus/34.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180823/microorganisms/images/staphylococcus/34.png","public_id":"microorganisms/images/staphylococcus/34","resource_type":"image","format":"png","width":449,"height":442,"caption":"Microbial strain 34","source_file":"Picture34.png","source_folder":"staphylococcus","source_sha256":"9f8ba2f7781de1b86cbc05e440a435df6b046bc14ded1f5e592613135f298a69"}'::jsonb), true)
WHERE display_order = 34;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180825/microorganisms/images/staphylococcus/35.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180825/microorganisms/images/staphylococcus/35.png","public_id":"microorganisms/images/staphylococcus/35","resource_type":"image","format":"png","width":450,"height":440,"caption":"Microbial strain 35","source_file":"Picture35.png","source_folder":"staphylococcus","source_sha256":"72030d6df80afa607c66cca6af6958b59a5f49dc67ecdab11cf92ee72eeadde7"}'::jsonb), true)
WHERE display_order = 35;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180828/microorganisms/images/staphylococcus/36.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180828/microorganisms/images/staphylococcus/36.png","public_id":"microorganisms/images/staphylococcus/36","resource_type":"image","format":"png","width":418,"height":434,"caption":"Microbial strain 36","source_file":"Picture36.png","source_folder":"staphylococcus","source_sha256":"f67206eb78c20352bb0bff97fb5c3ae33154a49623f4fba6d1f9a859d102401b"}'::jsonb), true)
WHERE display_order = 36;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180829/microorganisms/images/staphylococcus/37.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180829/microorganisms/images/staphylococcus/37.png","public_id":"microorganisms/images/staphylococcus/37","resource_type":"image","format":"png","width":455,"height":460,"caption":"Microbial strain 37","source_file":"Picture37.png","source_folder":"staphylococcus","source_sha256":"a102526a3a8bc58281b057c4c1ca0092aefb3bcf6f30c70586e447a1db39fa9d"}'::jsonb), true)
WHERE display_order = 37;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180831/microorganisms/images/staphylococcus/38.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180831/microorganisms/images/staphylococcus/38.png","public_id":"microorganisms/images/staphylococcus/38","resource_type":"image","format":"png","width":442,"height":458,"caption":"Microbial strain 38","source_file":"Picture38.png","source_folder":"staphylococcus","source_sha256":"a59d1d2b6f6172b6482c3683846c73350f9768c32a2c5c883abe730e9b25e00b"}'::jsonb), true)
WHERE display_order = 38;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180834/microorganisms/images/elicoli/39.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180834/microorganisms/images/elicoli/39.png","public_id":"microorganisms/images/elicoli/39","resource_type":"image","format":"png","width":428,"height":451,"caption":"Microbial strain 39","source_file":"Picture39.png","source_folder":"elicoli","source_sha256":"4abf1c2559ae63c733b076af23cc836b222adfaeddc503c14723af42777d561a"}'::jsonb), true)
WHERE display_order = 39;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180840/microorganisms/images/elicoli/40.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180840/microorganisms/images/elicoli/40.png","public_id":"microorganisms/images/elicoli/40","resource_type":"image","format":"png","width":486,"height":446,"caption":"Microbial strain 40","source_file":"Picture40.png","source_folder":"elicoli","source_sha256":"3db023278e1f906a2a153c32c3dfafa0078fe9c863c9f32a53de85c98e8386ac"}'::jsonb), true)
WHERE display_order = 40;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180849/microorganisms/images/elicoli/41.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180849/microorganisms/images/elicoli/41.png","public_id":"microorganisms/images/elicoli/41","resource_type":"image","format":"png","width":422,"height":437,"caption":"Microbial strain 41","source_file":"Picture41.png","source_folder":"elicoli","source_sha256":"d19d64518e06f23f73ff257260a630134ff0e121b11dfbf35b657df66a304cdd"}'::jsonb), true)
WHERE display_order = 41;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180853/microorganisms/images/elicoli/42.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180853/microorganisms/images/elicoli/42.png","public_id":"microorganisms/images/elicoli/42","resource_type":"image","format":"png","width":429,"height":443,"caption":"Microbial strain 42","source_file":"Picture42.png","source_folder":"elicoli","source_sha256":"d1e24e77bb1005a2a164f751902c1c1fd9b2a2c8b9e60ba07e53eacc0beaee00"}'::jsonb), true)
WHERE display_order = 42;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180856/microorganisms/images/elicoli/43.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180856/microorganisms/images/elicoli/43.png","public_id":"microorganisms/images/elicoli/43","resource_type":"image","format":"png","width":481,"height":446,"caption":"Microbial strain 43","source_file":"Picture43.png","source_folder":"elicoli","source_sha256":"b9f2eee971d0decfb8c53bffe3b691817a8529a197bc8debdaced40a13de2584"}'::jsonb), true)
WHERE display_order = 43;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180860/microorganisms/images/elicoli/44.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180860/microorganisms/images/elicoli/44.png","public_id":"microorganisms/images/elicoli/44","resource_type":"image","format":"png","width":420,"height":438,"caption":"Microbial strain 44","source_file":"Picture44.png","source_folder":"elicoli","source_sha256":"bdaf6e9555ed9bdfb47804921798190e4e0e99db89296181e889dfb0dfe57b1b"}'::jsonb), true)
WHERE display_order = 44;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180863/microorganisms/images/elicoli/45.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180863/microorganisms/images/elicoli/45.png","public_id":"microorganisms/images/elicoli/45","resource_type":"image","format":"png","width":429,"height":454,"caption":"Microbial strain 45","source_file":"Picture45.png","source_folder":"elicoli","source_sha256":"9d5f618d5d4db90120ca9c8178d364aacd532a2d7e07083324e4598dc6aae782"}'::jsonb), true)
WHERE display_order = 45;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180866/microorganisms/images/elicoli/46.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180866/microorganisms/images/elicoli/46.png","public_id":"microorganisms/images/elicoli/46","resource_type":"image","format":"png","width":475,"height":451,"caption":"Microbial strain 46","source_file":"Picture46.png","source_folder":"elicoli","source_sha256":"058a602d03e720ab6736e03d397022aface9f515e2144751d2df4e5bb922189e"}'::jsonb), true)
WHERE display_order = 46;

UPDATE microorganisms
SET media = jsonb_set(COALESCE(media, '{"images": [], "documents": []}'::jsonb), '{images}', jsonb_build_array('{"url":"http://res.cloudinary.com/dbpobcepn/image/upload/v1790180871/microorganisms/images/elicoli/47.png","secure_url":"https://res.cloudinary.com/dbpobcepn/image/upload/v1790180871/microorganisms/images/elicoli/47.png","public_id":"microorganisms/images/elicoli/47","resource_type":"image","format":"png","width":428,"height":446,"caption":"Microbial strain 47","source_file":"Picture47.png","source_folder":"elicoli","source_sha256":"706cd030ebbe953137c551d2ecbfd1d5cb698aa6f944d9e84cf210f306d3f437"}'::jsonb), true)
WHERE display_order = 47;

COMMIT;
